# This workflow will build and push a new container image to Amazon ECR,
# and then will deploy a new task definition to Amazon ECS, when there is a push to the "master" branch.
#
# To use this workflow, you will need to complete the following set-up steps:
#
# 1. Create an ECR repository to store your images.
#    For example: `aws ecr create-repository --repository-name my-ecr-repo --region us-east-2`.
#    Replace the value of the `ECR_REPOSITORY` environment variable in the workflow below with your repository's name.
#    Replace the value of the `AWS_REGION` environment variable in the workflow below with your repository's region.
#
# 2. Create an ECS task definition, an ECS cluster, and an ECS service.
#    For example, follow the Getting Started guide on the ECS console:
#      https://us-east-2.console.aws.amazon.com/ecs/home?region=us-east-2#/firstRun
#    Replace the value of the `ECS_SERVICE` environment variable in the workflow below with the name you set for the Amazon ECS service.
#    Replace the value of the `ECS_CLUSTER` environment variable in the workflow below with the name you set for the cluster.
#
# 3. Store your ECS task definition as a JSON file in your repository.
#    The format should follow the output of `aws ecs register-task-definition --generate-cli-skeleton`.
#    Replace the value of the `ECS_TASK_DEFINITION` environment variable in the workflow below with the path to the JSON file.
#    Replace the value of the `CONTAINER_NAME` environment variable in the workflow below with the name of the container
#    in the `containerDefinitions` section of the task definition.
#
# 4. Store an IAM user access key in GitHub Actions secrets named `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY`.
#    See the documentation for each action used below for the recommended IAM policies for this IAM user,
#    and best practices on handling the access key credentials.

name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build the Flask Docker image
      run: docker build -t my-flask-image -f Dockerfile.flask .
    - name: Build the Streamlit Docker image
      run: docker build -t my-streamlit-image -f Dockerfile.streamlit .
    - name: Login to AWS
      id: login-aws
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Push the Flask image to ECR
      run: |
        echo "Logging in to Amazon ECR..."
        $(aws ecr get-login --no-include-email)
        echo "Pushing Flask image..."
        docker push ${{ steps.push-image.outputs.registry }}/my-flask-image:latest
    - name: Push the Streamlit image to ECR
      run: |
        echo "Logging in to Amazon ECR..."
        $(aws ecr get-login --no-include-email)
        echo "Pushing Streamlit image..."
        docker push ${{ steps.push-image.outputs.registry }}/my-streamlit-image:latest
    - name: Deploy the Flask container to EC2
      run: |
        ssh -t -i my-key.pem ec2-user@my-instance "docker pull ${{ steps.push-image.outputs.registry }}/my-flask-image:latest && docker run -d -p 5000:5000 ${{ steps.push-image.outputs.registry }}/my-flask-image:latest"
    - name: Deploy the Streamlit container to EC2
      run: |
        ssh -t -i my-key.pem ec2-user@my-instance "docker pull ${{ steps.push-image.outputs.registry }}/my-streamlit-image:latest && docker run -d -p 8501:8501 ${{ steps.push-image.outputs.registry }}/my-streamlit-image:latest"
